# Generated by Django 4.2 on 2023-07-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
